### ISSUE TITLE
SSL_ERROR_BAD_CERT_DOMAIN

### ISSUE THREAD

**Issue by BastiHz** [Selbosh/selbosh.github.io#1]
Hello,
your github profile contains this link: https://www.selbydavid.com. But clicking that causes my browser to not load the website and instead warn me about a potential security risk:
```
SSL_ERROR_BAD_CERT_DOMAIN
Unable to communicate securely with peer: requested domain name does not match the server’s certificate.
```
This happens with firefox and edge. However, using this link works fine: https://selbydavid.com

**Comment by Selbosh** [comment]
Thanks. I will be sure to fix that now.
